// Code generated by gen-env/main.go; DO NOT EDIT.

package env

//go:wasmimport suffiks AddEnv
func AddEnv(ptr uint32, size uint32)

//go:wasmimport suffiks AddEnvFrom
func AddEnvFrom(ptr uint32, size uint32)

//go:wasmimport suffiks AddLabel
func AddLabel(ptr uint32, size uint32)

//go:wasmimport suffiks AddAnnotation
func AddAnnotation(ptr uint32, size uint32)

//go:wasmimport suffiks AddInitContainer
func AddInitContainer(ptr uint32, size uint32)

//go:wasmimport suffiks AddSidecar
func AddSidecar(ptr uint32, size uint32)

//go:wasmimport suffiks MergePatch
func MergePatch(ptr uint32, size uint32)

//go:wasmimport suffiks ValidationError
func ValidationError(ptr uint32, size uint32)

//go:wasmimport suffiks GetOwner
func GetOwner() uint64

//go:wasmimport suffiks GetSpec
func GetSpec() uint64

//go:wasmimport suffiks GetOld
func GetOld() uint64

//go:wasmimport suffiks CreateResource
func CreateResource(gvrPtr uint32, gvrSize uint32, specPtr uint32, specSize uint32) uint64

//go:wasmimport suffiks UpdateResource
func UpdateResource(gvrPtr uint32, gvrSize uint32, specPtr uint32, specSize uint32) uint64

//go:wasmimport suffiks DeleteResource
func DeleteResource(gvrPtr uint32, gvrSize uint32, namePtr uint32, nameSize uint32) uint64

// getResource returns a resource from the Kubernetes API server.
//
//go:wasmimport suffiks GetResource
func GetResource(gvrPtr uint32, gvrSize uint32, namePtr uint32, nameSize uint32) uint64
